In [47]:
!pip install haversine

Collecting haversine
  Downloading https://files.pythonhosted.org/packages/d7/26/78d4fadc73b7e4c3543f9d5401892cb9a3f4202be789984826033922ec5a/haversine-2.1.2-py2.py3-none-any.whl
Installing collected packages: haversine
Successfully installed haversine-2.1.2

In [2]:
import os
import pandas as pd 
from haversine import haversine, Unit

csvlist= os.listdir("C:/Users/Stu/Desktop/SMU_Bootcamp/SMUDAL201905DATA5/02-Homework/20-Tableau/Instructions/Data")

In [65]:
import os
import csv, glob

Dir = r"C:/Users/Stu/Desktop/SMU_Bootcamp/SMUDAL201905DATA5/02-Homework/20-Tableau/Instructions/Data"
Avg_Dir = r"C:/Users/Stu/Desktop/SMU_Bootcamp/SMUDAL201905DATA5/02-Homework/20-Tableau/Instructions/Data"

csv_file_list = glob.glob(os.path.join(Dir, '*.csv')) # returns the file list
print (csv_file_list)

with open(os.path.join(Avg_Dir, 'Output.csv'), 'w', newline='') as f:
    wf = csv.writer(f, lineterminator='\n')

    for files in csv_file_list:
        with open(files, 'r') as r: 
            next(r)                   # SKIP HEADERS
            rr = csv.reader(r)
            for row in rr:
                wf.writerow(row)

['C:/Users/Stu/Desktop/SMU_Bootcamp/SMUDAL201905DATA5/02-Homework/20-Tableau/Instructions/Data\\JC-201710-citibike-tripdata.csv', 'C:/Users/Stu/Desktop/SMU_Bootcamp/SMUDAL201905DATA5/02-Homework/20-Tableau/Instructions/Data\\JC-201711-citibike-tripdata.csv', 'C:/Users/Stu/Desktop/SMU_Bootcamp/SMUDAL201905DATA5/02-Homework/20-Tableau/Instructions/Data\\JC-201712-citibike-tripdata.csv', 'C:/Users/Stu/Desktop/SMU_Bootcamp/SMUDAL201905DATA5/02-Homework/20-Tableau/Instructions/Data\\JC-201801-citibike-tripdata.csv', 'C:/Users/Stu/Desktop/SMU_Bootcamp/SMUDAL201905DATA5/02-Homework/20-Tableau/Instructions/Data\\JC-201802-citibike-tripdata.csv', 'C:/Users/Stu/Desktop/SMU_Bootcamp/SMUDAL201905DATA5/02-Homework/20-Tableau/Instructions/Data\\JC-201803-citibike-tripdata.csv', 'C:/Users/Stu/Desktop/SMU_Bootcamp/SMUDAL201905DATA5/02-Homework/20-Tableau/Instructions/Data\\JC-201804-citibike-tripdata.csv', 'C:/Users/Stu/Desktop/SMU_Bootcamp/SMUDAL201905DATA5/02-Homework/20-Tableau/Instructions/Data\\JC-201805-citibike-tripdata.csv', 'C:/Users/Stu/Desktop/SMU_Bootcamp/SMUDAL201905DATA5/02-Homework/20-Tableau/Instructions/Data\\JC-201806-citibike-tripdata.csv', 'C:/Users/Stu/Desktop/SMU_Bootcamp/SMUDAL201905DATA5/02-Homework/20-Tableau/Instructions/Data\\JC-201807-citibike-tripdata.csv', 'C:/Users/Stu/Desktop/SMU_Bootcamp/SMUDAL201905DATA5/02-Homework/20-Tableau/Instructions/Data\\JC-201808-citibike-tripdata.csv', 'C:/Users/Stu/Desktop/SMU_Bootcamp/SMUDAL201905DATA5/02-Homework/20-Tableau/Instructions/Data\\JC-201809-citibike-tripdata.csv', 'C:/Users/Stu/Desktop/SMU_Bootcamp/SMUDAL201905DATA5/02-Homework/20-Tableau/Instructions/Data\\JC-201810-citibike-tripdata.csv', 'C:/Users/Stu/Desktop/SMU_Bootcamp/SMUDAL201905DATA5/02-Homework/20-Tableau/Instructions/Data\\JC-201811-citibike-tripdata.csv', 'C:/Users/Stu/Desktop/SMU_Bootcamp/SMUDAL201905DATA5/02-Homework/20-Tableau/Instructions/Data\\JC-201812-citibike-tripdata.csv', 'C:/Users/Stu/Desktop/SMU_Bootcamp/SMUDAL201905DATA5/02-Homework/20-Tableau/Instructions/Data\\JC-201901-citibike-tripdata.csv', 'C:/Users/Stu/Desktop/SMU_Bootcamp/SMUDAL201905DATA5/02-Homework/20-Tableau/Instructions/Data\\JC-201902-citibike-tripdata.csv', 'C:/Users/Stu/Desktop/SMU_Bootcamp/SMUDAL201905DATA5/02-Homework/20-Tableau/Instructions/Data\\JC-201903-citibike-tripdata.csv', 'C:/Users/Stu/Desktop/SMU_Bootcamp/SMUDAL201905DATA5/02-Homework/20-Tableau/Instructions/Data\\JC-201904-citibike-tripdata.csv', 'C:/Users/Stu/Desktop/SMU_Bootcamp/SMUDAL201905DATA5/02-Homework/20-Tableau/Instructions/Data\\JC-201905-citibike-tripdata.csv', 'C:/Users/Stu/Desktop/SMU_Bootcamp/SMUDAL201905DATA5/02-Homework/20-Tableau/Instructions/Data\\JC-201906-citibike-tripdata.csv', 'C:/Users/Stu/Desktop/SMU_Bootcamp/SMUDAL201905DATA5/02-Homework/20-Tableau/Instructions/Data\\JC-201907-citibike-tripdata.csv', 'C:/Users/Stu/Desktop/SMU_Bootcamp/SMUDAL201905DATA5/02-Homework/20-Tableau/Instructions/Data\\JC-201908-citibike-tripdata.csv', 'C:/Users/Stu/Desktop/SMU_Bootcamp/SMUDAL201905DATA5/02-Homework/20-Tableau/Instructions/Data\\JC-201909-citibike-tripdata.csv']

In [3]:
df = pd.read_csv("C:/Users/Stu/Desktop/SMU_Bootcamp/SMUDAL201905DATA5/02-Homework/20-Tableau/Instructions/Data/Output.csv", header=None)
df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,410,10/1/2017 0:03,10/1/2017 0:09,3213,Van Vorst Park,40.718489,-74.047727,3192,Liberty Light Rail,40.711242,-74.055701,26187,Subscriber,1976.0,1
1,412,10/1/2017 0:03,10/1/2017 0:10,3213,Van Vorst Park,40.718489,-74.047727,3192,Liberty Light Rail,40.711242,-74.055701,31768,Subscriber,1975.0,2
2,274,10/1/2017 0:24,10/1/2017 0:28,3195,Sip Ave,40.730743,-74.063784,3194,McGinley Square,40.725340,-74.067622,26311,Subscriber,1979.0,1
3,2198,10/1/2017 0:31,10/1/2017 1:07,3199,Newport Pkwy,40.728745,-74.032108,3183,Exchange Place,40.716247,-74.033459,31709,Subscriber,1994.0,1
4,166,10/1/2017 0:34,10/1/2017 0:36,3186,Grove St PATH,40.719586,-74.043117,3213,Van Vorst Park,40.718489,-74.047727,31759,Subscriber,1967.0,2

In [4]:
df.columns = ["tripduration_sec", "starttime", "stoptime", "start_station_id", "start_station_name", 
               "start_station_latitude", "start_station_longitude", "end_station_id", "end_station_name", "end_station_latitude"
              , "end_station_longitude", "bikeid", "usertype", "birth_year", "gender"]
df.head()

,tripduration_sec,starttime,stoptime,start_station_id,start_station_name,start_station_latitude,start_station_longitude,end_station_id,end_station_name,end_station_latitude,end_station_longitude,bikeid,usertype,birth_year,gender
0,410,10/1/2017 0:03,10/1/2017 0:09,3213,Van Vorst Park,40.718489,-74.047727,3192,Liberty Light Rail,40.711242,-74.055701,26187,Subscriber,1976.0,1
1,412,10/1/2017 0:03,10/1/2017 0:10,3213,Van Vorst Park,40.718489,-74.047727,3192,Liberty Light Rail,40.711242,-74.055701,31768,Subscriber,1975.0,2
2,274,10/1/2017 0:24,10/1/2017 0:28,3195,Sip Ave,40.730743,-74.063784,3194,McGinley Square,40.725340,-74.067622,26311,Subscriber,1979.0,1
3,2198,10/1/2017 0:31,10/1/2017 1:07,3199,Newport Pkwy,40.728745,-74.032108,3183,Exchange Place,40.716247,-74.033459,31709,Subscriber,1994.0,1
4,166,10/1/2017 0:34,10/1/2017 0:36,3186,Grove St PATH,40.719586,-74.043117,3213,Van Vorst Park,40.718489,-74.047727,31759,Subscriber,1967.0,2

In [5]:
df['start_coord'] = list(zip(df.start_station_latitude, df.start_station_longitude))
df.head()

,tripduration_sec,starttime,stoptime,start_station_id,start_station_name,start_station_latitude,start_station_longitude,end_station_id,end_station_name,end_station_latitude,end_station_longitude,bikeid,usertype,birth_year,gender,start_coord
0,410,10/1/2017 0:03,10/1/2017 0:09,3213,Van Vorst Park,40.718489,-74.047727,3192,Liberty Light Rail,40.711242,-74.055701,26187,Subscriber,1976.0,1,"(40.71848892, -74.04772663)"
1,412,10/1/2017 0:03,10/1/2017 0:10,3213,Van Vorst Park,40.718489,-74.047727,3192,Liberty Light Rail,40.711242,-74.055701,31768,Subscriber,1975.0,2,"(40.71848892, -74.04772663)"
2,274,10/1/2017 0:24,10/1/2017 0:28,3195,Sip Ave,40.730743,-74.063784,3194,McGinley Square,40.725340,-74.067622,26311,Subscriber,1979.0,1,"(40.73074263, -74.06378388)"
3,2198,10/1/2017 0:31,10/1/2017 1:07,3199,Newport Pkwy,40.728745,-74.032108,3183,Exchange Place,40.716247,-74.033459,31709,Subscriber,1994.0,1,"(40.728744799999994, -74.03210820000001)"
4,166,10/1/2017 0:34,10/1/2017 0:36,3186,Grove St PATH,40.719586,-74.043117,3213,Van Vorst Park,40.718489,-74.047727,31759,Subscriber,1967.0,2,"(40.71958612, -74.04311746)"

In [6]:
df['end_coord'] = list(zip(df.end_station_latitude, df.end_station_longitude))
df.head()

,tripduration_sec,starttime,stoptime,start_station_id,start_station_name,start_station_latitude,start_station_longitude,end_station_id,end_station_name,end_station_latitude,end_station_longitude,bikeid,usertype,birth_year,gender,start_coord,end_coord
0,410,10/1/2017 0:03,10/1/2017 0:09,3213,Van Vorst Park,40.718489,-74.047727,3192,Liberty Light Rail,40.711242,-74.055701,26187,Subscriber,1976.0,1,"(40.71848892, -74.04772663)","(40.711242299999995, -74.0557013)"
1,412,10/1/2017 0:03,10/1/2017 0:10,3213,Van Vorst Park,40.718489,-74.047727,3192,Liberty Light Rail,40.711242,-74.055701,31768,Subscriber,1975.0,2,"(40.71848892, -74.04772663)","(40.711242299999995, -74.0557013)"
2,274,10/1/2017 0:24,10/1/2017 0:28,3195,Sip Ave,40.730743,-74.063784,3194,McGinley Square,40.725340,-74.067622,26311,Subscriber,1979.0,1,"(40.73074263, -74.06378388)","(40.72533993, -74.06762213)"
3,2198,10/1/2017 0:31,10/1/2017 1:07,3199,Newport Pkwy,40.728745,-74.032108,3183,Exchange Place,40.716247,-74.033459,31709,Subscriber,1994.0,1,"(40.728744799999994, -74.03210820000001)","(40.7162469, -74.0334588)"
4,166,10/1/2017 0:34,10/1/2017 0:36,3186,Grove St PATH,40.719586,-74.043117,3213,Van Vorst Park,40.718489,-74.047727,31759,Subscriber,1967.0,2,"(40.71958612, -74.04311746)","(40.71848892, -74.04772663)"

In [7]:
dist= haversine((40.71848892, -74.04772663), (40.711242299999995, -74.0557013), unit='mi')
print(dist)

0.6520081506207169

In [8]:
df['coord_pair'] = list(zip(df.start_coord, df.end_coord))
df.head(50)

,tripduration_sec,starttime,stoptime,start_station_id,start_station_name,start_station_latitude,start_station_longitude,end_station_id,end_station_name,end_station_latitude,end_station_longitude,bikeid,usertype,birth_year,gender,start_coord,end_coord,coord_pair
0,410,10/1/2017 0:03,10/1/2017 0:09,3213,Van Vorst Park,40.718489,-74.047727,3192,Liberty Light Rail,40.711242,-74.055701,26187,Subscriber,1976.0,1,"(40.71848892, -74.04772663)","(40.711242299999995, -74.0557013)","((40.71848892, -74.04772663), (40.711242299999..."
1,412,10/1/2017 0:03,10/1/2017 0:10,3213,Van Vorst Park,40.718489,-74.047727,3192,Liberty Light Rail,40.711242,-74.055701,31768,Subscriber,1975.0,2,"(40.71848892, -74.04772663)","(40.711242299999995, -74.0557013)","((40.71848892, -74.04772663), (40.711242299999..."
2,274,10/1/2017 0:24,10/1/2017 0:28,3195,Sip Ave,40.730743,-74.063784,3194,McGinley Square,40.725340,-74.067622,26311,Subscriber,1979.0,1,"(40.73074263, -74.06378388)","(40.72533993, -74.06762213)","((40.73074263, -74.06378388), (40.72533993, -7..."
3,2198,10/1/2017 0:31,10/1/2017 1:07,3199,Newport Pkwy,40.728745,-74.032108,3183,Exchange Place,40.716247,-74.033459,31709,Subscriber,1994.0,1,"(40.728744799999994, -74.03210820000001)","(40.7162469, -74.0334588)","((40.728744799999994, -74.03210820000001), (40..."
4,166,10/1/2017 0:34,10/1/2017 0:36,3186,Grove St PATH,40.719586,-74.043117,3213,Van Vorst Park,40.718489,-74.047727,31759,Subscriber,1967.0,2,"(40.71958612, -74.04311746)","(40.71848892, -74.04772663)","((40.71958612, -74.04311746), (40.71848892, -7..."
5,129,10/1/2017 0:39,10/1/2017 0:41,3273,Manila & 1st,40.721651,-74.042884,3270,Jersey & 6th St,40.725289,-74.045572,31903,Subscriber,1989.0,1,"(40.72165072, -74.04288411)","(40.72528911, -74.04557168)","((40.72165072, -74.04288411), (40.72528911, -7..."
6,315,10/1/2017 0:46,10/1/2017 0:51,3186,Grove St PATH,40.719586,-74.043117,3213,Van Vorst Park,40.718489,-74.047727,31837,Subscriber,1981.0,2,"(40.71958612, -74.04311746)","(40.71848892, -74.04772663)","((40.71958612, -74.04311746), (40.71848892, -7..."
7,301,10/1/2017 0:47,10/1/2017 0:52,3186,Grove St PATH,40.719586,-74.043117,3213,Van Vorst Park,40.718489,-74.047727,26249,Subscriber,1976.0,1,"(40.71958612, -74.04311746)","(40.71848892, -74.04772663)","((40.71958612, -74.04311746), (40.71848892, -7..."
8,170,10/1/2017 0:48,10/1/2017 0:51,3205,JC Medical Center,40.716540,-74.049638,3276,Marin Light Rail,40.714584,-74.042817,31712,Subscriber,1976.0,1,"(40.71653978, -74.04963791)","(40.71458404, -74.04281706)","((40.71653978, -74.04963791), (40.71458404, -7..."
9,214,10/1/2017 0:54,10/1/2017 0:58,3186,Grove St PATH,40.719586,-74.043117,3481,York St,40.716490,-74.041050,31918,Subscriber,1962.0,1,"(40.71958612, -74.04311746)","(40.71649, -74.04105)","((40.71958612, -74.04311746), (40.71649, -74.0..."
10,1142,10/1/2017 1:04,10/1/2017 1:23,3198,Heights Elevator,40.748716,-74.040443,3269,Brunswick & 6th,40.726012,-74.050389,26209,Subscriber,1964.0,1,"(40.74871595, -74.04044329999999)","(40.72601173, -74.05038893)","((40.74871595, -74.04044329999999), (40.726011..."
11,433,10/1/2017 1:13,10/1/2017 1:21,3195,Sip Ave,40.730743,-74.063784,3280,Astor Place,40.719282,-74.071262,30356,Subscriber,1988.0,1,"(40.73074263, -74.06378388)","(40.7192822, -74.07126188)","((40.73074263, -74.06378388), (40.7192822, -74..."
12,316,10/1/2017 1:22,10/1/2017 1:27,3186,Grove St PATH,40.719586,-74.043117,3214,Essex Light Rail,40.712774,-74.036486,26229,Subscriber,1987.0,1,"(40.71958612, -74.04311746)","(40.712774200000005, -74.03648570000001)","((40.71958612, -74.04311746), (40.712774200000..."
13,104,10/1/2017 1:27,10/1/2017 1:29,3211,Newark Ave,40.721525,-74.046305,3270,Jersey & 6th St,40.725289,-74.045572,31697,Subscriber,1991.0,2,"(40.72152515, -74.04630454)","(40.72528911, -74.04557168)","((40.72152515, -74.04630454), (40.72528911, -7..."
14,326,10/1/2017 1:33,10/1/2017 1:39,3186,Grove St PATH,40.719586,-74.043117,3269,Brunswick & 6th,40.726012,-74.050389,31682,Subscriber,1994.0,1,"(40.71958612, -74.04311746)","(40.72601173, -74.05038893)","((40.71958612, -74.04311746), (40.72601173, -7..."
15,278,10/1/2017 1:41,10/1/2017 1:46,3205,JC Medical Center,40.716540,-74.049638,3279,Dixon Mills,40.721630,-74.049968,31725,Subscriber,1986.0,1,"(40.71653978, -74.04963791)","(40.72163014, -74.04996783)","((40.71653978, -74.04963791), (40.72163014, -7..."
16,171,10/1/2017 1:47,10/1/2017 1:50,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,31709,Subscriber,1983.0,1,"(40.7162469, -74.0334588)","(40.71241882, -74.03852552)","((40.7162469, -74.0334588), (40.71241882, -74...."
17,196,10/1/2017 1:48,10/1/2017 1:51,3187,Warren St,40.721124,-74.038051,3183,Exchange Place,40.716247,-74.033459,26259,Subscriber,1966.0,1,"(40.721123600000006, -74.03805095)","(40.7162469, -74.0334588)","((40.721123600000006, -74.03805095), (40.71624..."
18,562,10/1/2017 1:52,10/1/2017 2:01,3195,Sip Ave,40.730743,-74.063784,3191,Union St,40.718211,-74.083639,31745,Subscriber,1990.0,1,"(40.73074263, -74.06378388)","(40.71821129999999, -74.08363940000001)","((40.73074263, -74.06378388), (40.718211299999..."
19,378,10/1/2017 1:56,10/1/2017 2:03,3186,Grove St PATH,40.719586,-74.043117,3270,Jersey & 6th St,40.725289,-74.045572,31806,Subscriber,1967.0,1,"(40.71958612, -74.04311746)","(40.72528911, -74.04557168)","((40.71958612, -74.04311746), (40.72528911, -7..."
20,526,10/1/2017 1:57,10/1/2017 2:05,3186,Grove St PATH,40.719586,-74.043117,3269,Brunswick & 6th,40.726012,-74.050389,26197,Subscriber,1988.0,1,"(40.71958612, -74.04311746)","(40.72601173, -74.05038893)","((40.71958612, -74.04311746), (40.72601173, -7..."
21,1173,10/1/2017 2:11,10/1/2017 2:30,3183,Exchange Place,40.716247,-74.033459,3199,Newport Pkwy,40.728745,-74.032108,26259,Subscriber,1994.0,1,"(40.7162469, -74.0334588)","(40.728744799999994, -74.03210820000001)","((40.7162469, -74.0334588), (40.72874479999999..."
22,180,10/1/2017 2:23,10/1/2017 2:26,3186,Grove St PATH,40.719586,-74.043117,3276,Marin Light Rail,40.714584,-74.042817,31706,Subscriber,1989.0,1,"(40.71958612, -74.04311746)","(40.71458404, -74.04281706)","((40.71958612, -74.04311746), (40.71458404, -7..."
23,207,10/1/2017 2:31,10/1/2017 2:35,3211,Newark Ave,40.721525,-74.046305,3269,Brunswick & 6th,40.726012,-74.050389,29644,Subscriber,1985.0,1,"(40.72152515, -74.04630454)","(40.72601173, -74.05038893)","((40.72152515, -74.04630454), (40.72601173, -7..."
24,197,10/1/2017 2:31,10/1/2017 2:35,3211,Newark Ave,40.721525,-74.046305,3269,Brunswick & 6th,40.726012,-74.050389,31741,Subscriber,1986.0,2,"(40.72152515, -74.04630454)","(40.72601173, -74.05038893)","((40.72152515, -74.04630454), (40.72601173, -7..."
25,284,10/1/2017 2:47,10/1/2017 2:51,3186,Grove St PATH,40.719586,-74.043117,3209,Brunswick St,40.724176,-74.050656,31687,Subscriber,1987.0,1,"(40.71958612, -74.04311746)","(40.7241765, -74.05065640000001)","((40.71958612, -74.04311746), (40.7241765, -74..."
26,594,10/1/2017 2:47,10/1/2017 2:57,3186,Grove St PATH,40.719586,-74.043117,3278,Monmouth and 6th,40.725685,-74.048790,31693,Subscriber,1952.0,1,"(40.71958612, -74.04311746)","(40.72568548, -74.04879034)","((40.71958612, -74.04311746), (40.72568548, -7..."
27,220,10/1/2017 2:53,10/1/2017 2:57,3195,Sip Ave,40.730743,-74.063784,3225,Baldwin at Montgomery,40.723659,-74.064194,31710,Subscriber,1994.0,1,"(40.73074263, -74.06378388)","(40.7236589, -74.0641943)","((40.73074263, -74.06378388), (40.7236589, -74..."
28,109,10/1/2017 4:04,10/1/2017 4:06,3202,Newport PATH,40.727224,-74.033759,3480,WS Don't Use,0.000000,0.000000,29579,Subscriber,1993.0,1,"(40.7272235, -74.03375890000001)","(0.0, 0.0)","((40.7272235, -74.03375890000001), (0.0, 0.0))"
29,162,10/1/2017 4:33,10/1/2017 4:35,3195,Sip Ave,40.730743,-74.063784,3194,McGinley Square,40.725340,-74.067622,31825,Subscriber,1990.0,1,"(40.73074263, -74.06378388)","(40.72533993, -74.06762213)","((40.73074263, -74.06378388), (40.72533993, -7..."
30,226,10/1/2017 5:11,10/1/2017 5:15,3207,Oakland Ave,40.737604,-74.052478,3195,Sip Ave,40.730743,-74.063784,31866,Subscriber,1976.0,2,"(40.7376037, -74.05247829999999)","(40.73074263, -74.06378388)","((40.7376037, -74.05247829999999), (40.7307426..."
31,167,10/1/2017 5:21,10/1/2017 5:24,3184,Paulus Hook,40.714145,-74.033552,3267,Morris Canal,40.712419,-74.038526,31747,Subscriber,1986.0,1,"(40.7141454, -74.0335519)","(40.71241882, -74.03852552)","((40.7141454, -74.0335519), (40.71241882, -74...."
32,174,10/1/2017 5:37,10/1/2017 5:40,3186,Grove St PATH,40.719586,-74.043117,3481,York St,40.716490,-74.041050,31678,Subscriber,1978.0,1,"(40.71958612, -74.04311746)","(40.71649, -74.04105)","((40.71958612, -74.04311746), (40.71649, -74.0..."
33,583,10/1/2017 5:47,10/1/2017 5:56,3268,Lafayette Park,40.713464,-74.062859,3186,Grove St PATH,40.719586,-74.043117,31716,Subscriber,1984.0,1,"(40.71346383, -74.06285852)","(40.71958612, -74.04311746)","((40.71346383, -74.06285852), (40.71958612, -7..."
34,193,10/1/2017 5:53,10/1/2017 5:56,3194,McGinley Square,40.725340,-74.067622,3195,Sip Ave,40.730743,-74.063784,26217,Subscriber,1992.0,1,"(40.72533993, -74.06762213)","(40.73074263, -74.06378388)","((40.72533993, -74.06762213), (40.73074263, -7..."
35,262,10/1/2017 5:54,10/1/2017 5:59,3186,Grove St PATH,40.719586,-74.043117,3269,Brunswick & 6th,40.726012,-74.050389,31711,Subscriber,1981.0,1,"(40.71958612, -74.04311746)","(40.72601173, -74.05038893)","((40.71958612, -74.04311746), (40.72601173, -7..."
36,131,10/1/2017 6:22,10/1/2017 6:25,3279,Dixon Mills,40.721630,-74.049968,3186,Grove St PATH,40.719586,-74.043117,29623,Subscriber,1982.0,1,"(40.72163014, -74.04996783)","(40.71958612, -74.04311746)","((40.72163014, -74.04996783), (40.71958612, -7..."
37,191,10/1/2017 6:34,10/1/2017 6:37,3209,Brunswick St,40.724176,-74.050656,3186,Grove St PATH,40.719586,-74.043117,31762,Subscriber,1989.0,1,"(40.7241765, -74.05065640000001)","(40.71958612, -74.04311746)","((40.7241765, -74.05065640000001), (40.7195861..."
38,213,10/1/2017 6:43,10/1/2017 6:46,3194,McGinley Square,40.725340,-74.067622,3280,Astor Place,40.719282,-74.071262,31825,Subscriber,1964.0,1,"(40.72533993, -74.06762213)","(40.7192822, -74.07126188)","((40.72533993, -74.06762213), (40.7192822, -74..."
39,507,10/1/2017 6:49,10/1/2017 6:57,3199,Newport Pkwy,40.728745,-74.032108,3184,Paulus Hook,40.714145,-74.033552,26259,Subscriber,1963.0,1,"(40.728744799999994, -74.03210820000001)","(40.7141454, -74.0335519)","((40.728744799999994, -74.03210820000001), (40..."
40,1052,10/1/2017 6:52,10/1/2017 7:10,3217,Bayside Park,40.698651,-74.082080,3185,City Hall,40.717733,-74.043845,26163,Customer,NaN,0,"(40.69865054, -74.08207968)","(40.717732500000004, -74.04384499999999)","((40.69865054, -74.08207968), (40.717732500000..."
41,554,10/1/2017 6:54,10/1/2017 7:04,3225,Baldwin at Montgomery,40.723659,-74.064194,3186,Grove St PATH,40.719586,-74.043117,31842,Subscriber,1994.0,2,"(40.7236589, -74.0641943)","(40.71958612, -74.04311746)","((40.7236589, -74.0641943), (40.71958612, -74...."
42,1787,10/1/2017 7:10,10/1/2017 7:40,3201,Dey St,40.737711,-74.066921,3196,Riverview Park,40.744319,-74.043991,31864,Subscriber,1960.0,1,"(40.737711, -74.066921)","(40.7443187, -74.04399090000001)","((40.737711, -74.066921), (40.7443187, -74.043..."
43,234,10/1/2017 7:15,10/1/2017 7:19,3269,Brunswick & 6th,40.726012,-74.050389,3186,Grove St PATH,40.719586,-74.043117,31911,Subscriber,1980.0,1,"(40.72601173, -74.05038893)","(40.71958612, -74.04311746)","((40.72601173, -74.05038893), (40.71958612, -7..."
44,5303,10/1/2017 7:18,10/1/2017 8:46,3275,Columbus Drive,40.718355,-74.038914,3275,Columbus Drive,40.718355,-74.038914,31803,Subscriber,1985.0,1,"(40.718355200000005, -74.03891444)","(40.718355200000005, -74.03891444)","((40.718355200000005, -74.03891444), (40.71835..."
45,2648,10/1/2017 7:20,10/1/2017 8:04,3276,Marin Light Rail,40.714584,-74.042817,3276,Marin Light Rail,40.714584,-74.042817,31712,Customer,NaN,0,"(40.71458404, -74.04281706)","(40.71458404, -74.04281706)","((40.71458404, -74.04281706), (40.71458404, -7..."
46,292,10/1/2017 7:24,10/1/2017 7:29,3225,Baldwin at Montgomery,40.723659,-74.064194,3193,Lincoln Park,40.724605,-74.078406,29591,Subscriber,1994.0,1,"(40.7236589, -74.0641943)","(40.724605100000005, -74.07840595)","((40.7236589, -74.0641943), (40.72460510000000..."
47,84,10/1/2017 7:34,10/1/2017 7:35,3273,Manila & 1st,40.721651,-74.042884,3211,Newark Ave,40.721525,-74.046305,31813,Subscriber,1984.0,1,"(40.72165072, -74.04288411)","(40.72152515, -74.04630454)","((40.72165072, -74.04288411), (40.72152515, -7..."
48,453,10/1/2017 7:38,10/1/2017 7:46,3214,Essex Light Rail,40.712774,-74.036486,3187,Warren St,40.721124,-74.038051,31721,Subscriber,1986.0,1,"(40.712774200000005, -74.03648570000001)","(40.721123600000006, -74.03805095)","((40.712774200000005, -74.03648570000001), (40..."
49,873,10/1/2017 7:46,10/1/2017 8:00,3195,Sip Ave,40.730743,-74.063784,3225,Baldwin at Montgomery,40.723659,-74.064194,31866,Subscriber,1988.0,1,"(40.73074263, -74.06378388)","(40.7236589, -74.0641943)","((40.73074263, -74.06378388), (40.7236589, -74..."

In [73]:
distances=[]
i=0 
while i< len(df):
# for x in df:
#     count=0 
    miles= haversine((df.start_coord[i]),(df.end_coord[i]),unit='mi')
#     print(miles)
    i += 1 
    distances.append(miles)

In [74]:
print(len(distances))

740460

In [75]:
df['miles']= distances
df.head()

,tripduration_sec,starttime,stoptime,start_station_id,start_station_name,start_station_latitude,start_station_longitude,end_station_id,end_station_name,end_station_latitude,end_station_longitude,bikeid,usertype,birth_year,gender,start_coord,end_coord,coord_pair,miles
0,410,10/1/2017 0:03,10/1/2017 0:09,3213,Van Vorst Park,40.718489,-74.047727,3192,Liberty Light Rail,40.711242,-74.055701,26187,Subscriber,1976.0,1,"(40.71848892, -74.04772663)","(40.711242299999995, -74.0557013)","((40.71848892, -74.04772663), (40.711242299999...",0.652008
1,412,10/1/2017 0:03,10/1/2017 0:10,3213,Van Vorst Park,40.718489,-74.047727,3192,Liberty Light Rail,40.711242,-74.055701,31768,Subscriber,1975.0,2,"(40.71848892, -74.04772663)","(40.711242299999995, -74.0557013)","((40.71848892, -74.04772663), (40.711242299999...",0.652008
2,274,10/1/2017 0:24,10/1/2017 0:28,3195,Sip Ave,40.730743,-74.063784,3194,McGinley Square,40.725340,-74.067622,26311,Subscriber,1979.0,1,"(40.73074263, -74.06378388)","(40.72533993, -74.06762213)","((40.73074263, -74.06378388), (40.72533993, -7...",0.423952
3,2198,10/1/2017 0:31,10/1/2017 1:07,3199,Newport Pkwy,40.728745,-74.032108,3183,Exchange Place,40.716247,-74.033459,31709,Subscriber,1994.0,1,"(40.728744799999994, -74.03210820000001)","(40.7162469, -74.0334588)","((40.728744799999994, -74.03210820000001), (40...",0.866414
4,166,10/1/2017 0:34,10/1/2017 0:36,3186,Grove St PATH,40.719586,-74.043117,3213,Van Vorst Park,40.718489,-74.047727,31759,Subscriber,1967.0,2,"(40.71958612, -74.04311746)","(40.71848892, -74.04772663)","((40.71958612, -74.04311746), (40.71848892, -7...",0.252994

In [76]:
df['feet']= round(df.miles*5280)
df.head()

,tripduration_sec,starttime,stoptime,start_station_id,start_station_name,start_station_latitude,start_station_longitude,end_station_id,end_station_name,end_station_latitude,end_station_longitude,bikeid,usertype,birth_year,gender,start_coord,end_coord,coord_pair,miles,feet
0,410,10/1/2017 0:03,10/1/2017 0:09,3213,Van Vorst Park,40.718489,-74.047727,3192,Liberty Light Rail,40.711242,-74.055701,26187,Subscriber,1976.0,1,"(40.71848892, -74.04772663)","(40.711242299999995, -74.0557013)","((40.71848892, -74.04772663), (40.711242299999...",0.652008,3443.0
1,412,10/1/2017 0:03,10/1/2017 0:10,3213,Van Vorst Park,40.718489,-74.047727,3192,Liberty Light Rail,40.711242,-74.055701,31768,Subscriber,1975.0,2,"(40.71848892, -74.04772663)","(40.711242299999995, -74.0557013)","((40.71848892, -74.04772663), (40.711242299999...",0.652008,3443.0
2,274,10/1/2017 0:24,10/1/2017 0:28,3195,Sip Ave,40.730743,-74.063784,3194,McGinley Square,40.725340,-74.067622,26311,Subscriber,1979.0,1,"(40.73074263, -74.06378388)","(40.72533993, -74.06762213)","((40.73074263, -74.06378388), (40.72533993, -7...",0.423952,2238.0
3,2198,10/1/2017 0:31,10/1/2017 1:07,3199,Newport Pkwy,40.728745,-74.032108,3183,Exchange Place,40.716247,-74.033459,31709,Subscriber,1994.0,1,"(40.728744799999994, -74.03210820000001)","(40.7162469, -74.0334588)","((40.728744799999994, -74.03210820000001), (40...",0.866414,4575.0
4,166,10/1/2017 0:34,10/1/2017 0:36,3186,Grove St PATH,40.719586,-74.043117,3213,Van Vorst Park,40.718489,-74.047727,31759,Subscriber,1967.0,2,"(40.71958612, -74.04311746)","(40.71848892, -74.04772663)","((40.71958612, -74.04311746), (40.71848892, -7...",0.252994,1336.0

In [77]:
# df= df.drop(columns=['start_station_latitude'])
# df.head()

In [78]:
df.to_csv('df.csv', encoding='utf-8', index=False)

In [48]:
# from datetime import datetime
# dates =  datetime.strptime('10/1/2017 0:36', '%m/%d/%Y %H:%M')
# print(dates)

2017-10-01 00:36:00

In [53]:
# start_datetime=[]
# for x in df.starttime:
#     date= datetime.strptime(x, '%m/%d/%Y %H:%M:%S')
#     print(date)

ValueError: time data '10/1/2017 0:03' does not match format '%m/%d/%Y %H:%M:%S'